### ISSUE TITLE
Add get-key-with-modifiers and get-key-blocking-with-modifiers

### ISSUE THREAD

**Issue by Martin-S-Weber** [MultiMUD/clojure-lanterna#1]
as per [sjl's lanterna's Pull Request 18](https://github.com/sjl/clojure-lanterna/pull/18), add get-key with modifier info
Review diff by @keedon

**Comment by MultiMUD** [comment]
Done with Adam's pull request.
`get-keystroke` and `get-keystroke-blocking` added with it that provide the necessary functionality. Currently only on `lanterna3` branch.
