### ISSUE TITLE
Odd characters in Hello, World example

### ISSUE THREAD

**Issue by eigenhombre** [MultiMUD/clojure-lanterna#15]
When I run

```
(let [term (t/get-terminal :unix)]
  (t/in-terminal term
    (t/put-string term "Hello!  Press any key to end.")
    (t/get-key-blocking term)))
```

in text mode, I get funny characters:

![screen shot 2015-01-18 at 12 04 39 pm](https://cloud.githubusercontent.com/assets/382668/5793474/3559ea92-9f0a-11e4-929c-0a4d0e074b22.png)

On OS-X, this happens when I `:unix` or `:text`.  Haven't tried any other OS.  It's not there when I `:swing`.  Any thoughts?

**Comment by eigenhombre** [comment]
Clarification: If I give the extra coordinate arguments to `put-string`, the extra junk characters don't appear.

**Comment by Martin-S-Weber** [comment]
Try running with lein trampoline run / lein trampoline repl.
Leiningen performs an extra level of I/O redirection which renders the terminal helpless to actually interpret and reply to the escape codes.

**Comment by MultiMUD** [comment]
OP's :+1: makes me think this is resolved. Documentation now also explicitly states that examples should be run with `lein trampoline`.
